name: Main branch

on:
  push:
    branches:
      - main-test

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/setup
      - uses: ./github/actions/basic-preflight-check
