name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: ./github/actions/setup
      - uses: ./github/actions/basic-preflight-check
