name: Pull request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup
      - uses: ./.github/actions/basic-preflight-check
